[general]
import = [
  "~/.config/alacritty/themes/tn.toml"
]

[window]
dimensions = { columns = 98, lines = 25 }
opacity = 0.97
padding = { x = 10, y = 10 }
dynamic_padding = true


[font]
size = 13
size = 13
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }

[selection]
save_to_clipboard = true
