#!/bin/bash
# reflector --list

if [ "$(which curl)" != "curl not found" ]; then
  check_country=$(curl -s https://ipinfo.io/country)
fi

if [ "$1" = "-lc" ]; then
  # mirrors -lc
  sudo reflector -p "https,http" -c "kz,pl,cn,de,$check_country" --sort rate -l 20 -f 10 --threads 5 --save /etc/pacman.d/mirrorlist
elif [ "$1" = "-c" ]; then
  # mirrors -c
  sudo reflector -p "https,http" -c "$check_country" --sort rate -l 20 -f 10 --threads 5 --save /etc/pacman.d/mirrorlist
else
  # mirrors
  sudo reflector --verbose -p "https,http" --sort rate -l 20 -f 10 --threads 5 --save /etc/pacman.d/mirrorlist
fi

cat /etc/pacman.d/mirrorlist
sudo pacman -Syy
